### ISSUE TITLE
LineUp takes 5 minutes to start

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.lineup#3]
On a recent windows 7 machine with decent hardware specs.

```

INFO: org.caleydo.core: Start animator
INFO: org.caleydo.core: Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]
INFO: org.caleydo.core.view.ViewManager@4b1ab736: Registering view: demo.ARcpRankTableDemoView$GLView@4ed00001
Error: org.caleydo.core.view.opengl.canvas.MyAnimator: display error: SWT-GLCanvas[Realized true,
    jogamp.opengl.windows.wgl.WindowsOnscreenWGLDrawable,
    Factory   jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory@fae7b6e,
    handle    0x0,
    Drawable size 1360x657,
    SWT size 1360x657]java.lang.NullPointerException
    at org.caleydo.vis.lineup.ui.column.AColumnHeaderUI.onMainPick(AColumnHeaderUI.java:670)
    at org.caleydo.vis.lineup.ui.column.AColumnHeaderUI$2.pick(AColumnHeaderUI.java:124)
    at org.caleydo.core.view.opengl.picking.PickingListenerComposite.pick(PickingListenerComposite.java:38)
    at org.caleydo.core.view.opengl.picking.SimplePickingManager$PickingEntry.fire(SimplePickingManager.java:27)
    at org.caleydo.core.view.opengl.picking.APickingEntry.fire(APickingEntry.java:66)
    at org.caleydo.core.view.opengl.picking.APickingManager.fireListeners(APickingManager.java:256)
    at org.caleydo.core.view.opengl.picking.APickingManager.doPicking(APickingManager.java:144)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.pickingPass(AGLElementView.java:243)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:190)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:588)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:572)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:572)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:176)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

INFO: org.caleydo.core: Start animator
INFO: org.caleydo.core: Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]
INFO: org.caleydo.core.view.ViewManager@4b1ab736: Registering view: demo.ARcpRankTableDemoView$GLView@4ed00002
```

**Comment by myhrvold** [comment]
Specs (via Speccy)

OS: Windows 7 Home Premium 64-bit SP1

CPU: Intel Core i5 2450M @ 2.50GHz
        Sandy Bridge 32nm Technology

RAM: 8.00GB Dual-Channel DDR3 @ 665MHz (9-9-9-24)

Motherboard: ASUSTeK Computer Inc. U46SM (CPU 1)

Graphics: Generic PnP Monitor (1366x768@60Hz)
VE245 (1920x1080@60Hz)
Intel HD Graphics 3000 (ASUStek Computer Inc)
1024MB NVIDIA GeForce GT 630M (ASUStek Computer Inc)

The largest other process being run at the time was Dropbox (synced and in the background, not uploading/downloading files)

**Comment by sgratzl** [comment]
Does it only happen once, or every time when you start LineUp?. 
Does it also happen when you start Caleydo?
Are you launching LineUp from Eclipse Source or the bundled version?

**Comment by myhrvold** [comment]
I've only started it up 3 times -- it's happened each time. I've launched it from the LineUp bundle file. I've just tried from the Caleydo one, and it seems faster but of course I have to download 17 MB file to test out, so it still takes ~2 min or so.

Here's what that log looks like:

```
INFO: org.caleydo.core.internal.Application: Starting Caleydo
OK: org.caleydo.core.internal.Application: Environment Variables:
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\flint\AppData\Roaming
CLASSPATH=.;C:\Program Files (x86)\Java\jre7\lib\ext\QTJava.zip
COMPUTERNAME=FLINT-PC
ComSpec=C:\Windows\system32\cmd.exe
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
FP_NO_HOST_CHECK=NO
HOME=C:\Users\flint
HOMEDRIVE=C:
HOMEPATH=\Users\flint
LOCALAPPDATA=C:\Users\flint\AppData\Local
LOGONSERVER=\\FLINT-PC
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2a07
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
Path=C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\MATLAB\R2013a\runtime\win64;C:\Program Files\MATLAB\R2013a\bin;C:\Program Files\MATLAB\R2012a\runtime\win64;C:\Program Files\MATLAB\R2012a\bin;C:\Anaconda;C:\Anaconda\Scripts;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Users\flint\AppData\Local\Enthought\Canopy32\User\Scripts;
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
QTJAVA=C:\Program Files (x86)\Java\jre7\lib\ext\QTJava.zip
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\flint\AppData\Local\Temp
TMP=C:\Users\flint\AppData\Local\Temp
USERDOMAIN=flint-PC
USERNAME=flint
USERPROFILE=C:\Users\flint
VBOX_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
asl.log=Destination=file
configsetroot=C:\Windows\ConfigSetRoot
windir=C:\Windows

OK: org.caleydo.core.internal.Application: System Properties:
awt.toolkit=sun.awt.windows.WToolkit
eclipse.application=org.caleydo.core.application
eclipse.commands=-os
win32
-ws
win32
-arch
x86_64
-showsplash
-launcher
C:\Program Files\Caleydo\Caleydo.exe
-name
Caleydo
--launcher.library
C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.200.v20130521-0416\eclipse_1503.dll
-startup
C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
--launcher.overrideVmargs
-exitdata
146c_9c
-data
@noDefault
-vm
C:\Windows\system32\javaw.exe

eclipse.home.location=file:/C:/Program Files/Caleydo/
eclipse.launcher=C:\Program Files\Caleydo\Caleydo.exe
eclipse.launcher.name=Caleydo
eclipse.p2.data.area=@config.dir/../p2
eclipse.p2.profile=DefaultProfile
eclipse.product=org.caleydo.core.product
eclipse.startTime=1379677102915
eclipse.vm=C:\Windows\system32\javaw.exe
eclipse.vmargs=-Xms512m
-Xmx2048m
-XX:MaxPermSize=256m
-Djava.util.logging.config.file=data/logging/logging.properties
-jar
C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar

equinox.use.ds=true
file.encoding=Cp1252
file.encoding.pkg=sun.io
file.separator=\
gosh.args=--nointeractive
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
java.class.version=51.0
java.endorsed.dirs=C:\Program Files\Java\jre7\lib\endorsed
java.ext.dirs=C:\Program Files\Java\jre7\lib\ext;C:\Windows\Sun\Java\lib\ext
java.home=C:\Program Files\Java\jre7
java.io.tmpdir=C:\Users\flint\AppData\Local\Temp\
java.library.path=C:\Windows\system32;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\MATLAB\R2013a\runtime\win64;C:\Program Files\MATLAB\R2013a\bin;C:\Program Files\MATLAB\R2012a\runtime\win64;C:\Program Files\MATLAB\R2012a\bin;C:\Anaconda;C:\Anaconda\Scripts;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Users\flint\AppData\Local\Enthought\Canopy32\User\Scripts;;.
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.7.0-b147
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.7
java.util.logging.config.file=data/logging/logging.properties
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.7.0
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.7
java.vm.vendor=Oracle Corporation
java.vm.version=21.0-b17
line.separator=

org.eclipse.equinox.launcher.splash.handle=2427318
org.eclipse.equinox.launcher.splash.location=C:\Users\flint\.eclipse\1542257127_win32_win32_x86_64\configuration\org.eclipse.equinox.launcher\org.caleydo.core_3.0.2\splash.bmp
org.eclipse.equinox.simpleconfigurator.configUrl=file:org.eclipse.equinox.simpleconfigurator/bundles.info
org.eclipse.update.reconcile=false
org.osgi.framework.executionenvironment=OSGi/Minimum-1.0,OSGi/Minimum-1.1,OSGi/Minimum-1.2,JRE-1.1,J2SE-1.2,J2SE-1.3,J2SE-1.4,J2SE-1.5,JavaSE-1.6,JavaSE-1.7
org.osgi.framework.language=en
org.osgi.framework.os.name=Windows7
org.osgi.framework.os.version=6.1.0
org.osgi.framework.processor=x86-64
org.osgi.framework.system.capabilities=osgi.ee; osgi.ee="OSGi/Minimum"; version:List<Version>="1.0, 1.1, 1.2",osgi.ee; osgi.ee="JRE"; version:List<Version>="1.0, 1.1",osgi.ee; osgi.ee="JavaSE"; version:List<Version>="1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7"
org.osgi.framework.system.packages=javax.accessibility,javax.activation,javax.activity,javax.annotation,javax.annotation.processing,javax.crypto,javax.crypto.interfaces,javax.crypto.spec,javax.imageio,javax.imageio.event,javax.imageio.metadata,javax.imageio.plugins.bmp,javax.imageio.plugins.jpeg,javax.imageio.spi,javax.imageio.stream,javax.jws,javax.jws.soap,javax.lang.model,javax.lang.model.element,javax.lang.model.type,javax.lang.model.util,javax.management,javax.management.loading,javax.management.modelmbean,javax.management.monitor,javax.management.openmbean,javax.management.relation,javax.management.remote,javax.management.remote.rmi,javax.management.timer,javax.naming,javax.naming.directory,javax.naming.event,javax.naming.ldap,javax.naming.spi,javax.net,javax.net.ssl,javax.print,javax.print.attribute,javax.print.attribute.standard,javax.print.event,javax.rmi,javax.rmi.CORBA,javax.rmi.ssl,javax.script,javax.security.auth,javax.security.auth.callback,javax.security.auth.kerberos,javax.security.auth.login,javax.security.auth.spi,javax.security.auth.x500,javax.security.cert,javax.security.sasl,javax.sound.midi,javax.sound.midi.spi,javax.sound.sampled,javax.sound.sampled.spi,javax.sql,javax.sql.rowset,javax.sql.rowset.serial,javax.sql.rowset.spi,javax.swing,javax.swing.border,javax.swing.colorchooser,javax.swing.event,javax.swing.filechooser,javax.swing.plaf,javax.swing.plaf.basic,javax.swing.plaf.metal,javax.swing.plaf.multi,javax.swing.plaf.nimbus,javax.swing.plaf.synth,javax.swing.table,javax.swing.text,javax.swing.text.html,javax.swing.text.html.parser,javax.swing.text.rtf,javax.swing.tree,javax.swing.undo,javax.tools,javax.transaction,javax.transaction.xa,javax.xml,javax.xml.bind,javax.xml.bind.annotation,javax.xml.bind.annotation.adapters,javax.xml.bind.attachment,javax.xml.bind.helpers,javax.xml.bind.util,javax.xml.crypto,javax.xml.crypto.dom,javax.xml.crypto.dsig,javax.xml.crypto.dsig.dom,javax.xml.crypto.dsig.keyinfo,javax.xml.crypto.dsig.spec,javax.xml.datatype,javax.xml.namespace,javax.xml.parsers,javax.xml.soap,javax.xml.stream,javax.xml.stream.events,javax.xml.stream.util,javax.xml.transform,javax.xml.transform.dom,javax.xml.transform.sax,javax.xml.transform.stax,javax.xml.transform.stream,javax.xml.validation,javax.xml.ws,javax.xml.ws.handler,javax.xml.ws.handler.soap,javax.xml.ws.http,javax.xml.ws.soap,javax.xml.ws.spi,javax.xml.ws.spi.http,javax.xml.ws.wsaddressing,javax.xml.xpath,org.ietf.jgss,org.omg.CORBA,org.omg.CORBA_2_3,org.omg.CORBA_2_3.portable,org.omg.CORBA.DynAnyPackage,org.omg.CORBA.ORBPackage,org.omg.CORBA.portable,org.omg.CORBA.TypeCodePackage,org.omg.CosNaming,org.omg.CosNaming.NamingContextExtPackage,org.omg.CosNaming.NamingContextPackage,org.omg.Dynamic,org.omg.DynamicAny,org.omg.DynamicAny.DynAnyFactoryPackage,org.omg.DynamicAny.DynAnyPackage,org.omg.IOP,org.omg.IOP.CodecFactoryPackage,org.omg.IOP.CodecPackage,org.omg.Messaging,org.omg.PortableInterceptor,org.omg.PortableInterceptor.ORBInitInfoPackage,org.omg.PortableServer,org.omg.PortableServer.CurrentPackage,org.omg.PortableServer.POAManagerPackage,org.omg.PortableServer.POAPackage,org.omg.PortableServer.portable,org.omg.PortableServer.ServantLocatorPackage,org.omg.SendingContext,org.omg.stub.java.rmi,org.w3c.dom,org.w3c.dom.bootstrap,org.w3c.dom.css,org.w3c.dom.events,org.w3c.dom.html,org.w3c.dom.ls,org.w3c.dom.ranges,org.w3c.dom.stylesheets,org.w3c.dom.traversal,org.w3c.dom.views,org.w3c.dom.xpath,org.xml.sax,org.xml.sax.ext,org.xml.sax.helpers
org.osgi.framework.uuid=c07d4a2d-e921-0013-14e9-d98e2d4ee5ab
org.osgi.framework.vendor=Eclipse
org.osgi.framework.version=1.7.0
org.osgi.supports.framework.extension=true
org.osgi.supports.framework.fragment=true
org.osgi.supports.framework.requirebundle=true
os.arch=amd64
os.name=Windows 7
os.version=6.1
osgi.arch=x86_64
osgi.bundles=reference:file:org.eclipse.equinox.simpleconfigurator_1.0.400.v20130327-2119.jar@1:start
osgi.bundles.defaultStartLevel=4
osgi.bundlestore=C:\Users\flint\.eclipse\1542257127_win32_win32_x86_64\configuration\org.eclipse.osgi\bundles
osgi.configuration.area=file:/C:/Users/flint/.eclipse/1542257127_win32_win32_x86_64/configuration/
osgi.framework=file:/c:/Program Files/Caleydo/plugins/org.eclipse.osgi_3.9.0.v20130529-1710.jar
osgi.framework.extensions=
osgi.framework.shape=jar
osgi.framework.version=3.9.0.v20130529-1710
osgi.install.area=file:/C:/Program Files/Caleydo/
osgi.logfile=C:\Users\flint\.eclipse\1542257127_win32_win32_x86_64\configuration\1379677110444.log
osgi.manifest.cache=C:\Users\flint\.eclipse\1542257127_win32_win32_x86_64\configuration\org.eclipse.osgi\manifests
osgi.nl=en_US
osgi.os=win32
osgi.sharedConfiguration.area=file:/c:/Program Files/Caleydo/configuration/
osgi.splashLocation=C:\Users\flint\.eclipse\1542257127_win32_win32_x86_64\configuration\org.eclipse.equinox.launcher\org.caleydo.core_3.0.2\splash.bmp
osgi.splashPath=platform:/base/plugins/org.caleydo.core
osgi.syspath=c:\Program Files\Caleydo\plugins
osgi.ws=win32
path.separator=;
sun.arch.data.model=64
sun.boot.class.path=C:\Program Files\Java\jre7\lib\resources.jar;C:\Program Files\Java\jre7\lib\rt.jar;C:\Program Files\Java\jre7\lib\sunrsasign.jar;C:\Program Files\Java\jre7\lib\jsse.jar;C:\Program Files\Java\jre7\lib\jce.jar;C:\Program Files\Java\jre7\lib\charsets.jar;C:\Program Files\Java\jre7\classes
sun.boot.library.path=C:\Program Files\Java\jre7\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar -os win32 -ws win32 -arch x86_64 -showsplash -launcher C:\Program Files\Caleydo\Caleydo.exe -name Caleydo --launcher.library C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.200.v20130521-0416\eclipse_1503.dll -startup C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar --launcher.overrideVmargs -exitdata 146c_9c -data @noDefault -vm C:\Windows\system32\javaw.exe -vmargs -Xms512m -Xmx2048m -XX:MaxPermSize=256m -Djava.util.logging.config.file=data/logging/logging.properties -jar C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
sun.java.launcher=SUN_STANDARD
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=Service Pack 1
user.country=US
user.dir=C:\Program Files\Caleydo
user.home=C:\Users\flint
user.language=en
user.name=flint
user.script=
user.timezone=America/New_York
user.variant=

INFO: org.caleydo.core.internal.Application: creating wizard shell
INFO: org.caleydo.core.internal.Application: open wizard
INFO: org.caleydo.core.internal.Application: wizard done
INFO: org.caleydo.core: File copied from C:\Users\flint\.caleydo_3.0\temp_load\workbench.xmi to C:\Users\flint\.caleydo_3.0\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi
INFO: org.caleydo.datadomain.pathway.parser.KEGGParser: Start parsing KEGG pathways.
INFO: org.caleydo.datadomain.pathway.parser.KEGGParser: Finished parsing KEGG pathways.
INFO: org.caleydo.core.startup.LoadProjectStartupProcedure@4379344a: Load serialized project
Error: org.caleydo.core.serialize.ProjectManager: Error Loading Project from
C:\Users\flint\.caleydo_3.0\temp_load\java.lang.RuntimeException: Could not create JAXBContexts
    at org.caleydo.core.serialize.SerializationManager.createNewProjectContext(SerializationManager.java:66)
    at org.caleydo.core.serialize.SerializationManager.<init>(SerializationManager.java:57)
    at org.caleydo.core.serialize.SerializationManager.get(SerializationManager.java:74)
    at org.caleydo.core.manager.GeneralManager.getSerializationManager(GeneralManager.java:192)
    at org.caleydo.core.serialize.ProjectManager.loadData(ProjectManager.java:162)
    at org.caleydo.core.serialize.ProjectManager.loadProjectData(ProjectManager.java:116)
    at org.caleydo.core.startup.LoadProjectStartupProcedure.run(LoadProjectStartupProcedure.java:120)
    at org.caleydo.core.internal.Application$3.run(Application.java:243)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration does not have a no-arg default constructor.
    this problem is related to the following location:
        at org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration
        at public org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration org.caleydo.core.util.clusterer.initialization.ClusterConfiguration.getClusterAlgorithmConfiguration()
        at org.caleydo.core.util.clusterer.initialization.ClusterConfiguration
        at public java.util.ArrayList org.caleydo.core.io.DataProcessingDescription.getColumnClusterConfigurations()
        at org.caleydo.core.io.DataProcessingDescription
        at public org.caleydo.core.io.DataProcessingDescription org.caleydo.core.io.DataSetDescription.getDataProcessingDescription()
        at org.caleydo.core.io.DataSetDescription
        at public org.caleydo.core.io.DataSetDescription org.caleydo.core.data.datadomain.ADataDomain.getDataSetDescription()
        at org.caleydo.core.data.datadomain.ADataDomain
        at org.caleydo.core.data.datadomain.ATableBasedDataDomain
        at public org.caleydo.core.data.datadomain.ATableBasedDataDomain org.caleydo.core.serialize.DataDomainSerializationData.getDataDomain()
        at org.caleydo.core.serialize.DataDomainSerializationData

    at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(Unknown Source)
    at com.sun.xml.internal.bind.v2.ContextFactory.createContext(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
    at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
    at javax.xml.bind.ContextFinder.find(Unknown Source)
    at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
    at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
    at org.caleydo.core.serialize.SerializationManager.createNewProjectContext(SerializationManager.java:64)
    ... 8 more

INFO: org.caleydo.core: Start animator
INFO: org.caleydo.core: Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]
INFO: org.caleydo.core.view.ViewManager@371aa8e8: Registering view: org.caleydo.view.dvi.GLDataViewIntegrator@5a440001
INFO: org.caleydo.core: Start animator
INFO: org.caleydo.core: Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]
INFO: org.caleydo.core.view.ViewManager@371aa8e8: Registering view: StratomeX
INFO: org.caleydo.core: Stop animator
INFO: org.caleydo.core.serialize.ProjectManager: Saving Plugin Data
INFO: org.caleydo.core.serialize.ProjectManager: Saving Data
Error: org.caleydo.core.serialize.ProjectManager: Error Saving Auto-Save Projectjava.lang.RuntimeException: Could not create JAXBContexts
    at org.caleydo.core.serialize.SerializationManager.createNewProjectContext(SerializationManager.java:66)
    at org.caleydo.core.serialize.SerializationManager.<init>(SerializationManager.java:57)
    at org.caleydo.core.serialize.SerializationManager.get(SerializationManager.java:74)
    at org.caleydo.core.manager.GeneralManager.getSerializationManager(GeneralManager.java:192)
    at org.caleydo.core.serialize.ProjectManager.saveData(ProjectManager.java:437)
    at org.caleydo.core.serialize.ProjectManager.access$4(ProjectManager.java:434)
    at org.caleydo.core.serialize.ProjectManager$3.run(ProjectManager.java:390)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration does not have a no-arg default constructor.
    this problem is related to the following location:
        at org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration
        at public org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration org.caleydo.core.util.clusterer.initialization.ClusterConfiguration.getClusterAlgorithmConfiguration()
        at org.caleydo.core.util.clusterer.initialization.ClusterConfiguration
        at public java.util.ArrayList org.caleydo.core.io.DataProcessingDescription.getColumnClusterConfigurations()
        at org.caleydo.core.io.DataProcessingDescription
        at public org.caleydo.core.io.DataProcessingDescription org.caleydo.core.io.DataSetDescription.getDataProcessingDescription()
        at org.caleydo.core.io.DataSetDescription
        at public org.caleydo.core.io.DataSetDescription org.caleydo.core.data.datadomain.ADataDomain.getDataSetDescription()
        at org.caleydo.core.data.datadomain.ADataDomain
        at org.caleydo.core.data.datadomain.ATableBasedDataDomain
        at public org.caleydo.core.data.datadomain.ATableBasedDataDomain org.caleydo.core.serialize.DataDomainSerializationData.getDataDomain()
        at org.caleydo.core.serialize.DataDomainSerializationData

    at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(Unknown Source)
    at com.sun.xml.internal.bind.v2.ContextFactory.createContext(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
    at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
    at javax.xml.bind.ContextFinder.find(Unknown Source)
    at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
    at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
    at org.caleydo.core.serialize.SerializationManager.createNewProjectContext(SerializationManager.java:64)
    ... 7 more

INFO: org.caleydo.core.serialize.ProjectManager: Saved Recent Project
INFO: org.caleydo.core.internal.Application: Bye bye!
```

**Comment by sgratzl** [comment]
@myhrvold you should really update your java installation, as far as I can see you have 1.7.0. The current version is 1.7.0_40

**Comment by myhrvold** [comment]
@sgratzl Just updated it! Should I try again to see if it's faster?

**Comment by sgratzl** [comment]
> @sgratzl Just updated it! Should I try again to see if it's faster?

yes please. 

It it doesn't solve your problem, at least you shouldn't observe the `org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration does not have a no-arg default constructor.` error, anymore.

**Comment by myhrvold** [comment]
Seems a little faster. Takes 3 min to load Caleydo; ~2 min 30 sec is loading data.

For LineUp, it now takes ~30 sec instead of 5 min.

**Comment by myhrvold** [comment]
LineUp log:

INFO: org.caleydo.core: Start animator
INFO: org.caleydo.core: Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]
INFO: org.caleydo.core.view.ViewManager@c1e908b: Registering view: demo.ARcpRankTableDemoView$GLView@71ad0001

**Comment by sgratzl** [comment]
that is acceptable at the moment
